# Exploratory Data Analysis Phase
- This phase explores the relationship between variables, what dtypes each variable has, distribution of data, detecting abnormalities and statistical evaluations.

In [1]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Import
DATASET_FILEPATH = '../dataset/raw/'
DATASET_FILENAME = 'skill-scarcity-index.csv'

# Pandas import
df = pd.read_csv(DATASET_FILEPATH+DATASET_FILENAME, index_col=0)

In [ ]:
# First 10 Rows
df.head(10)

,category,skill_name,demand_count,demand_pct,median_days_open,salary_premium_pct,repost_rate_pct,scarcity_score
snapshot_date,,,,,,,,
2026-07-12,ai,A/B Testing,115,4.7,1.0,3.9,2.0,49.2
2026-07-12,ai,Agile / Scrum,63,2.6,1.0,42.5,14.0,62.9
2026-07-12,ai,AI Agents,153,6.3,NaN,45.5,5.9,72.0
2026-07-12,ai,AI Coding Tools,32,1.3,NaN,NaN,0.0,0.0
2026-07-12,ai,Airflow,54,2.2,9.0,-38.7,16.2,57.2
2026-07-12,ai,AWS,259,10.6,0.0,-29.2,11.2,31.0
2026-07-12,ai,Azure,221,9.0,0.0,-46.9,19.5,28.3
2026-07-12,ai,BigQuery,43,1.8,4.0,NaN,22.2,75.5
2026-07-12,ai,C#,42,1.7,0.0,-31.5,7.2,25.0
2026-07-12,ai,C++,66,2.7,1.0,-10.9,18.0,60.4

In [21]:
# Show category unique values
df['category'].unique()

<ArrowStringArray>
['ai', 'data', 'devops', 'engineering', 'product', 'security']
Length: 6, dtype: str

In [ ]:
# DTypes
df.dtypes

category                  str
skill_name                str
demand_count            int64
demand_pct            float64
median_days_open      float64
salary_premium_pct    float64
repost_rate_pct       float64
scarcity_score        float64
dtype: object

In [13]:
# Info
df.info()

<class 'pandas.DataFrame'>
Index: 4933 entries, 2026-07-12 to 2026-08-05
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category            4933 non-null   str
 1   skill_name          4933 non-null   str
 2   demand_count        4933 non-null   int64
 3   demand_pct          4933 non-null   float64
 4   median_days_open    3898 non-null   float64
 5   salary_premium_pct  3894 non-null   float64
 6   repost_rate_pct     4933 non-null   float64
 7   scarcity_score      4933 non-null   float64
dtypes: float64(5), int64(1), str(2)
memory usage: 464.7 KB

Inferences:
- 1035 null values in ```median_days_open```, 1039 null values in ```salary_premium_pct```
- Dtypes are right as they were.
- valid? yes, but will do a deeper investigation for those null values before proceeding what to do with them.

In [ ]:
# Describe numeric columns
df.describe()

,demand_count,demand_pct,median_days_open,salary_premium_pct,repost_rate_pct,scarcity_score
count,4933.000000,4933.000000,3898.000000,3894.000000,4933.000000,4933.000000
mean,189.864991,3.482506,11.601591,7.337365,8.641597,40.934867
std,358.644820,6.127848,20.065420,46.851702,10.852761,21.807479
min,10.000000,0.100000,0.000000,-71.100000,0.000000,0.000000
25%,23.000000,0.500000,0.000000,-28.400000,0.000000,27.200000
50%,55.000000,1.300000,1.000000,-3.800000,5.800000,40.200000
75%,178.000000,3.600000,15.000000,32.500000,13.200000,56.700000
max,3422.000000,82.300000,108.000000,224.200000,100.000000,100.000000

In [18]:
# Explore column with null values
median_days_open_null_sum = df['median_days_open'].isnull().sum()
salary_premium_pct_null_sum = df['salary_premium_pct'].isnull().sum()
print(f"Null Count (Median Days Open): {median_days_open_null_sum}")
print(f"Null Count (Salary Premium %): {salary_premium_pct_null_sum}")

Null Count (Median Days Open): 1035
Null Count (Salary Premium %): 1039

^ Values verified the inference of null values from .info()

In [24]:
# Show rows that have null values in the 'median_days_open' column
null_median_days = df[df['median_days_open'].isnull()]
print(f"Number of rows with Null Values: {len(null_median_days)}")
null_median_days

Number of rows with Null Values: 1035

,category,skill_name,demand_count,demand_pct,median_days_open,salary_premium_pct,repost_rate_pct,scarcity_score
snapshot_date,,,,,,,,
2026-07-12,ai,AI Agents,153,6.3,NaN,45.5,5.9,72.0
2026-07-12,ai,AI Coding Tools,32,1.3,NaN,NaN,0.0,0.0
2026-07-12,ai,Incident Response,17,0.7,NaN,NaN,0.0,0.0
2026-07-12,ai,Prompt Engineering,45,1.8,NaN,NaN,0.0,0.0
2026-07-12,ai,Salesforce,17,0.7,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-08-05,security,Elasticsearch,11,0.5,NaN,NaN,8.3,83.7
2026-08-05,security,GraphQL,10,0.4,NaN,96.4,0.0,49.5
2026-08-05,security,MCP,10,0.4,NaN,NaN,0.0,0.0
2026-08-05,security,MLflow,14,0.6,NaN,NaN,0.0,0.0
2026-08-05,security,ServiceNow,17,0.7,NaN,-15.0,0.0,17.7

In [26]:
# Show rows that have null values in the 'salary_premium_pct' 
null_salary_premium_pct = df[df['salary_premium_pct'].isnull()]
print(f"Number of rows with Null Values: {len(null_salary_premium_pct)}")
null_salary_premium_pct

Number of rows with Null Values: 1039

,category,skill_name,demand_count,demand_pct,median_days_open,salary_premium_pct,repost_rate_pct,scarcity_score
snapshot_date,,,,,,,,
2026-07-12,ai,AI Coding Tools,32,1.3,NaN,NaN,0.0,0.0
2026-07-12,ai,BigQuery,43,1.8,4.0,NaN,22.2,75.5
2026-07-12,ai,Datadog,31,1.3,82.0,NaN,0.0,61.5
2026-07-12,ai,Incident Response,17,0.7,NaN,NaN,0.0,0.0
2026-07-12,ai,MongoDB,51,2.1,0.0,NaN,16.4,25.8
...,...,...,...,...,...,...,...,...
2026-08-05,security,Jira,13,0.5,36.0,NaN,0.0,37.3
2026-08-05,security,MCP,10,0.4,NaN,NaN,0.0,0.0
2026-08-05,security,MLflow,14,0.6,NaN,NaN,0.0,0.0
2026-08-05,security,Node.js,29,1.2,52.0,NaN,0.0,50.3
2026-08-05,security,TypeScript,57,2.4,28.0,NaN,0.0,35.4

In [28]:
#  Rows where either 'median_days_open' or 'salary_premium_pct' is null
null_rows = df[df['median_days_open'].isnull() | df['salary_premium_pct'].isnull()]
print(f"Number of rows with Null Values: {len(null_rows)}")
null_rows

Number of rows with Null Values: 1617

,category,skill_name,demand_count,demand_pct,median_days_open,salary_premium_pct,repost_rate_pct,scarcity_score
snapshot_date,,,,,,,,
2026-07-12,ai,AI Agents,153,6.3,NaN,45.5,5.9,72.0
2026-07-12,ai,AI Coding Tools,32,1.3,NaN,NaN,0.0,0.0
2026-07-12,ai,BigQuery,43,1.8,4.0,NaN,22.2,75.5
2026-07-12,ai,Datadog,31,1.3,82.0,NaN,0.0,61.5
2026-07-12,ai,Incident Response,17,0.7,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-08-05,security,MCP,10,0.4,NaN,NaN,0.0,0.0
2026-08-05,security,MLflow,14,0.6,NaN,NaN,0.0,0.0
2026-08-05,security,Node.js,29,1.2,52.0,NaN,0.0,50.3
2026-08-05,security,ServiceNow,17,0.7,NaN,-15.0,0.0,17.7
2026-08-05,security,TypeScript,57,2.4,28.0,NaN,0.0,35.4